import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs';
import Weather from '../components/Weather';
import { SpinnerDotted } from 'spinners-react';

export default function Home() {
	const [city, setCity] = useState('');
	const [weather, setWeather] = useState({});
	const [loading, setLoading] = useState(false);

	const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

	const fetchWeather = (event) => {
		event.preventDefault();
		setLoading(true);
		axios.get(url).then((response) => {
			setWeather(response.data);
			console.log(response.data);
		});
		setCity('');
		setLoading(false);
	};

	if (loading) {
		return <SpinnerDotted />;
	} else {
		return (
			<div className=''>
				<Head>
					<title>NextJS Weather App</title>
					<meta
						name='description'
						content='Generated by create next app'
					/>
					<link
						rel='icon'
						href='/favicon.ico'
					/>
				</Head>

				{/* OVERLAY */}
				<div className='absolute top-0 left-0 right-0 bottom-0 bg-black/80 z-[1]' />
				<Image
					layout='fill'
					className='object-fill'
					src='https://images.unsplash.com/photo-1580193769210-b8d1c049a7d9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=874&q=80'
					alt='nature background'
				/>
				{/* SEARCH */}
				<div className='relative flex justify-between items-center max-w-[500px] m-auto pt-4 z-10 text-white'>
					<form
						onSubmit={fetchWeather}
						className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 rounded-xl text-white'
					>
						<div>
							<input
								onChange={(event) => setCity(event.target.value)}
								className='bg-transparent border-none text-white focus:outline-none text-xl'
								type='text'
								placeholder='Search city'
							/>
						</div>
						<button onClick={fetchWeather}>
							<BsSearch size={22} />
						</button>
					</form>
				</div>

				{/* WEATHER */}
				{weather.main && <Weather data={weather} />}
			</div>
		);
	}
}
