import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs';

export default function Home() {
	const [city, setCity] = useState('');
	const [weather, setWeather] = useState({});
	const [loading, setLoading] = useState(false);

	const url = `https://api.openweathermap.org/data/2.5/weather?q=dubai&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

	const fetchWeather = (event) => {
		event.preventDefault();
		setLoading(true);
		axios.get(url).then((response) => {
			setWeather(response.data);
			console.log(response.data);
		});
		setCity('');
		setLoading(false);
	};

	return (
		<div>
			<Head>
				<title>NextJS Weather App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>

			<button onClick={fetchWeather}>Fetch Data</button>
		</div>
	);
}
