import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs';

export default function Home() {
	const [city, setCity] = useState('');
	const [weather, setWeather] = useState({});
	const [loading, setLoading] = useState(false);

	const url = `https://api.openweathermap.org/data/2.5/weather?q=dubai&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

	const fetchWeather = (event) => {
		event.preventDefault();
		setLoading(true);
		axios.get(url).then((response) => {
			setWeather(response.data);
			console.log(response.data);
		});
		setCity('');
		setLoading(false);
	};

	return (
		<div>
			<Head>
				<title>NextJS Weather App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>

			<div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]'>
				<Image
					layout='fill'
					className='object-fill'
					src='https://images.unsplash.com/photo-1580193769210-b8d1c049a7d9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=874&q=80'
				/>
			</div>
		</div>
	);
}
